
language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer install --prefer-source --no-interaction

script:
  - php ./vendor/bin/codecept run unit,acceptance --coverage-xml

after_success:
- travis_retry php ./vendor/bin/php-coveralls
